[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "kusama-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

  [[relaychain.nodes]]
  name = "charlie"
  validator = true

  [[relaychain.nodes]]
  name = "dave"
  validator = true

[[parachains]]
id = 1000
chain = "statemine-local"

  [[parachains.collators]]
  name = "collator1"
  image = "docker.io/parity/genesis-node:latest"
  command = "genesis-node"

  [[parachains.collators]]
  name = "collator2"
  image = "docker.io/parity/genesis-node:latest"
  command = "genesis-node"
